import { Inter } from "next/font/google";
import "../globals.css";
import Script from 'next/script'
import Footer from "../component/Footer";
import Header from "../component/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  deScription: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
   
    
      <body className={`${inter.className} ` }>
     
      <div id="page" className="site">
<Header/>
        {children}


       <Footer/>
      <a id="back-to-top" href="#" class="show"><i class="flaticon-up-arrow"></i></a>
      </div>
      
    <Script src="/js/jquery.min.js"></Script>
    <Script src="/js/jquery.magnific-popup.min.js"></Script>
    <Script src="/js/jquery.isotope.min.js"></Script>
    <Script src="/js/owl.carousel.min.js"></Script>
    <Script src="/js/easypiechart.min.js"></Script>
    <Script src="/js/jquery.countdown.min.js"></Script>
    <Script src="/js/Scripts.js"></Script>
    <Script src="/js/header-mobile.js"></Script>

    <Script  src="/plugins/revolution/revolution/js/jquery.themepunch.tools.min.js"></Script>
    <Script  src="/plugins/revolution/revolution/js/jquery.themepunch.revolution.min.js"></Script>

    <Script  src="/plugins/revolution/revolution/js/extensions/revolution-plugin.js"></Script>

    <Script  src="/js/rev-Script-2.js"></Script>
    {/* <Script src="/js/royal_preloader.min.js"></Script> */}
   
      </body>

    </html>
  );
}
